
import java.sql.ResultSet;
import java.sql.Statement;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Kasun Gunarathne
 */
public class summary extends javax.swing.JFrame {

    /**
     * Creates new form summary
     */
    public summary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Mango");

        jLabel2.setText("Sugar");

        jLabel3.setText("Water");

        jLabel4.setText("Bottle");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Stock");

        jButton1.setText("Pie Chart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel5)))
                .addContainerGap(187, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        String type = "Mango";
        int quan = 0;
        int pquan = 0;
        int wquan = 0;
        try {
            Statement s1 = DBConnect.getConnection().createStatement();
            Statement s2 = DBConnect.getConnection().createStatement();
            Statement s3 = DBConnect.getConnection().createStatement();
            ResultSet r1 = s1.executeQuery("select quantity from material where type='" + type + "'");
            ResultSet r2 = s2.executeQuery("select quantity from toproduction where material='" + type + "'");
            ResultSet r3 = s3.executeQuery("select quantity from wastage where type='" + type + "'");
            while (r1.next()) {
                quan += r1.getInt("quantity");
            }
            while (r2.next()) {
                pquan += r2.getInt("quantity");
            }
            while (r3.next()) {
                wquan += r3.getInt("quantity");
            }
            int cquan = quan - (pquan + wquan);
            jTextField1.setText(Integer.toString(cquan));
        } catch (Exception e) {
            System.out.println("Exception = " + e);
        }

        type = "Sugar";
        quan = 0;
        pquan = 0;
        wquan = 0;
        try {
            Statement s1 = DBConnect.getConnection().createStatement();
            Statement s2 = DBConnect.getConnection().createStatement();
            Statement s3 = DBConnect.getConnection().createStatement();
            ResultSet r1 = s1.executeQuery("select quantity from material where type='" + type + "'");
            ResultSet r2 = s2.executeQuery("select quantity from toproduction where material='" + type + "'");
            ResultSet r3 = s3.executeQuery("select quantity from wastage where type='" + type + "'");
            while (r1.next()) {
                quan += r1.getInt("quantity");
            }
            while (r2.next()) {
                pquan += r2.getInt("quantity");
            }
            while (r3.next()) {
                wquan += r3.getInt("quantity");
            }
            int cquan = quan - (pquan + wquan);
            jTextField2.setText(Integer.toString(cquan));
        } catch (Exception e) {
            System.out.println("Exception = " + e);
        }

        type = "Water";
        quan = 0;
        pquan = 0;
        wquan = 0;
        try {
            Statement s1 = DBConnect.getConnection().createStatement();
            Statement s2 = DBConnect.getConnection().createStatement();
            Statement s3 = DBConnect.getConnection().createStatement();
            ResultSet r1 = s1.executeQuery("select quantity from material where type='" + type + "'");
            ResultSet r2 = s2.executeQuery("select quantity from toproduction where material='" + type + "'");
            ResultSet r3 = s3.executeQuery("select quantity from wastage where type='" + type + "'");
            while (r1.next()) {
                quan += r1.getInt("quantity");
            }
            while (r2.next()) {
                pquan += r2.getInt("quantity");
            }
            while (r3.next()) {
                wquan += r3.getInt("quantity");
            }
            int cquan = quan - (pquan + wquan);
            jTextField3.setText(Integer.toString(cquan));
        } catch (Exception e) {
            System.out.println("Exception = " + e);
        }

        type = "Bottle";
        quan = 0;
        pquan = 0;
        wquan = 0;
        try {
            Statement s1 = DBConnect.getConnection().createStatement();
            Statement s2 = DBConnect.getConnection().createStatement();
            Statement s3 = DBConnect.getConnection().createStatement();
            ResultSet r1 = s1.executeQuery("select quantity from material where type='" + type + "'");
            ResultSet r2 = s2.executeQuery("select quantity from toproduction where material='" + type + "'");
            ResultSet r3 = s3.executeQuery("select quantity from wastage where type='" + type + "'");
            while (r1.next()) {
                quan += r1.getInt("quantity");
            }
            while (r2.next()) {
                pquan += r2.getInt("quantity");
            }
            while (r3.next()) {
                wquan += r3.getInt("quantity");
            }
            int cquan = quan - (pquan + wquan);
            jTextField4.setText(Integer.toString(cquan));
        } catch (Exception e) {
            System.out.println("Exception = " + e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int mango = Integer.parseInt(jTextField1.getText());
        int sugar = Integer.parseInt(jTextField2.getText());
        int water = Integer.parseInt(jTextField3.getText());
        int bottle = Integer.parseInt(jTextField4.getText());

        DefaultPieDataset pieDataset = new DefaultPieDataset();
        pieDataset.setValue("Mango", new Integer(mango));
        pieDataset.setValue("Sugar", new Integer(sugar));
        pieDataset.setValue("Water", new Integer(water));
        pieDataset.setValue("Bottle", new Integer(bottle));
        JFreeChart chart = ChartFactory.createPieChart("Pie Chart", pieDataset, true, true, true);
        PiePlot p = (PiePlot) chart.getPlot();
        ChartFrame frame = new ChartFrame("Pie Chart", chart);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        frame.setSize(450, 500);

        //p.setForegroundAlpha(TOP_ALIGNMENT);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new summary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
